language: php

jsdecena:
  - php72-composer:latest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cd api
  - touch database/todo.sqlite
  - cp .env.testing .env
  - composer install --no-interaction
  - composer dump-autoload

script:
  - vendor/bin/phpunit --coverage-text
